global:
  n_mels: 128
  sample_rate: 48000
  win_length: 1024
  hop_length: 480
  fmin: 40
  fmax: 8000
  n_fft: 1024
  chromagram_n_fft: 8192
  hidden_dim_scaling: 1
  valid_length: 300
  max_timestep: 3000 # melspec_maxlength
  label_smoothing: 0.08

  model_name: mandarin_opencpop-extension_singing
  random_seed: 114514
  device: cuda
  binary_data_folder: data/binary/

preprocessing:
  data_folder: data/
  ignored_phonemes:
    - AP
    - SP
    - <AP>
    - <SP>
    - ''
    - pau
    - cl
  valid_set_size: 100
  pitch_extractor: rmvpe # parselmouth

train:
  test_data_folder: data/test/
  num_gpus: 1
  random_seed: 114514
  precision: 32-true # bf16-mixed
  batch_size: 32
