global:
  n_mels: 128
  sample_rate: 48000
  win_length: 1024
  hop_length: 480
  fmin: 40
  fmax: 8000
  n_fft: 1024
  chromagram_n_fft: 8192
  hidden_dim_scaling: 1
  valid_length: 300
  max_timestep: 3000 # melspec_maxlength

  model_name: mandarin_opencpop-extension_singing
  random_seed: 114514
  device: cuda
  binary_data_folder: data/binary/

preprocessing:
  data_folder: data/
  ignored_phonemes:
    - AP
    - SP
    - <AP>
    - <SP>
    - ''
    - pau
    - cl
  valid_set_size: 100
  pitch_extractor: rmvpe # parselmouth

train:
  # settings
  float32_matmul_precision: high

  # dataloader
  batch_size: 3
  dataloader_workers: 15

  # model
  learning_rate: 0.001 #0.001
  weight_decay: 0.1
  hidden_dims: 64
  init_type: kaiming_normal # kaiming_normal, kaiming_uniform, xavier_normal, xavier_uniform
  label_smoothing: 0.08
  # global: n_mels
  # global: max_timestep

  # trainer
  accelerator: gpu
  devices: auto # num_devices
  precision: 32-true # bf16-mixed , 32-true
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm #value
  val_check_interval: 500 # 0.25

  use_pretrained_model: False
  pretrained_model_path: ''

  test_data_folder: data/test/

  max_steps: 10000
  valid_intervals: 200
  test_intervals: 1000
  save_intervals: 1000
