model_name: mandarin_opencpop-extension_singing
sample_rate: 48000
n_fft: 1024
hop_length: 480
n_mels: 128
chromagram_n_fft: 8192
hidden_dim_scaling: 1
valid_length: 300
melspec_maxlength: 3000
label_smoothing: 0.08
ignore_phonemes:
  - AP
  - SP
  - <AP>
  - <SP>
  - ''
  - pau
  - cl
random_seed: 114
device: cuda

train:
  batch_size_sup: 24
  batch_size_wsp: 24
  weight_decay: 0.01
  learning_rate: 0.0015
  max_steps: 10001
  test_interval: 500
  save_ckpt_start: 8000
  save_ckpt_interval: 200
  val_interval: 100