mel_spec:
  n_mels: 128
  sample_rate: 48000
  win_length: 1024
  hop_length: 480
  n_fft: 2048
  fmin: 40
  fmax: 32000
  clamp: 0.00001

global:
  model_name: mandarin_opencpop-extension_singing
  binary_data_folder: data/binary/
  max_frame_num: 3000 # melspec_maxlength
  input_feature_dims: 128 # usually equals to n_mels
  device: cuda

preprocessing:
  data_folder: data/
  valid_set_size: 15
  ignored_phonemes:
    - AP
    - SP
    - <AP>
    - <SP>
    - ''
    - pau
    - cl

train:
  # settings
  float32_matmul_precision: high
  random_seed: 114514

  # dataloader
  dataloader_workers: 15
  oversampling_weights: [ 1, 1, 1 ]
  batch_max_length: 40 # unit: seconds
  binning_length: 1000 # unit: seconds
  drop_last: False

  # model
  learning_rate: 0.001 #0.001
  weight_decay: 0.1
  hidden_dims: 64
  init_type: kaiming_normal # kaiming_normal, kaiming_uniform, xavier_normal, xavier_uniform
  label_smoothing: 0.08
  # global: n_mels
  # global: max_frame_num

  # trainer
  accelerator: auto
  devices: auto # num_devices
  precision: 32-true # bf16-mixed , 32-true
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm #value
  val_check_interval: 50 # 0.25
  max_steps: 10000

  use_pretrained_model: False
  pretrained_model_path: ''

  test_data_folder: data/test/

infer:
  chromagram_n_fft: 8192
