global:
  model_name: mandarin_opencpop-extension_singing
  n_mels: 128
  sample_rate: 48000
  win_length: 1024
  hop_length: 480
  fmin: 40
  fmax: 8000
  n_fft: 1024
  chromagram_n_fft: 8192
  hidden_dim_scaling: 1
  valid_length: 300
  melspec_maxlength: 3000
  label_smoothing: 0.08

  random_seed: 114
  device: cuda

preprocessing:
  data_folder: data/
  binary_data_folder: data/binary/
  test_data_folder: data/test/
  ignored_phonemes:
    - AP
    - SP
    - <AP>
    - <SP>
    - ''
    - pau
    - cl
  valid_set_size: 100
  pitch_extractor: rmvpe # parselmouth